pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "hello"
      ls -ltrh
      sudo apt update
      sudo apt upgrade
      #sudo apt install postfix
      sudo apt install mailutils
      mail -s "this is for test " majid.khatibshahidi@atoss.com